import type { OsceCard, OsceStation } from "../schema.js";

type CardInput = Omit<
  OsceCard,
  | "repeatable"
  | "sensitive"
  | "earlyRapportPenalty"
  | "unlockedBy"
  | "availableOnlyInWindowOfCue"
  | "revealsFacts"
  | "satisfies"
  | "penalises"
  | "rapportDelta"
  | "examinerReaction"
  | "triggersCue"
  | "triggersCurveball"
> &
  Partial<
    Pick<
      OsceCard,
      | "repeatable"
      | "sensitive"
      | "earlyRapportPenalty"
      | "unlockedBy"
      | "availableOnlyInWindowOfCue"
      | "revealsFacts"
      | "satisfies"
      | "penalises"
      | "rapportDelta"
      | "examinerReaction"
      | "triggersCue"
      | "triggersCurveball"
    >
  >;

function card(input: CardInput): OsceCard {
  return {
    repeatable: false,
    sensitive: false,
    earlyRapportPenalty: 0,
    unlockedBy: [],
    availableOnlyInWindowOfCue: null,
    revealsFacts: [],
    satisfies: [],
    penalises: [],
    rapportDelta: 0,
    examinerReaction: "none",
    triggersCue: null,
    triggersCurveball: false,
    ...input,
  };
}

export const CHEST_TIGHTNESS_STATION: OsceStation = {
  id: "osce_hx_001",
  type: "history_taking",
  reviewStatus: "needs_clinician_review",
  title: "Chest Tightness on the Stairs",
  setting: "Medical outpatient clinic",
  clockSeconds: 480,
  readingSeconds: 60,
  candidateInstructions:
    "You are a medical student in an outpatient clinic. Take a focused history from Mr Daniel Otieno, who has attended because of chest tightness. Do not examine the patient. You will be asked three questions by the examiner when the consultation ends.",
  examinerNote: "Candidates should not examine the patient in this station.",
  patient: {
    name: "Mr Daniel Otieno",
    age: 54,
    sex: "Male",
    avatar: {
      skinTone: "deep_brown",
      hair: "short_black_grey",
      outfit: "teal_shirt",
      ageCues: "middle_aged",
    },
    personality:
      "A practical bus driver who minimises his symptoms as indigestion, answers briefly when guarded, and is quietly frightened of dying like his father.",
    openingLine: "Morning, doctor. It's probably only indigestion, but my wife insisted I come.",
    initialExpression: "guarded",
  },
  facts: {
    presenting_site: "The pressure is in the centre of his chest.",
    presenting_character: "It feels like a tight, band-like pressure rather than a sharp pain.",
    presenting_onset_duration: "It began about three weeks ago.",
    presenting_exertion: "It occurs when climbing stairs or walking uphill.",
    presenting_relief: "It eases after a few minutes of rest.",
    presenting_severity: "At its worst it is about 6/10 and makes him stop walking.",
    presenting_pattern: "Episodes have become a little easier to provoke over three weeks.",
    presenting_previous: "He had not experienced this before the last three weeks.",
    presenting_not_pleuritic: "It is not brought on by breathing and is not sharp.",
    presenting_not_food: "Meals do not bring it on and antacids have not helped.",
    associated_breathlessness: "He becomes breathless during the exertional episodes.",
    associated_sweating: "He felt sweaty during one episode.",
    associated_radiation: "On occasion it spreads to his left arm and jaw.",
    red_flag_rest_pain:
      "Two days ago he had the same pressure while sitting at home; it lasted about 15 minutes.",
    no_syncope_palpitations: "He has not fainted and has not noticed palpitations.",
    self_treatment_antacids: "He tried antacids without meaningful relief.",
    self_treatment_ibuprofen: "He occasionally took ibuprofen, also without clear benefit.",
    pmh_hypertension: "Hypertension was diagnosed several years ago.",
    pmh_no_diabetes: "He has never been diagnosed with diabetes.",
    pmh_cholesterol_unknown: "He does not know his cholesterol level.",
    medication_stopped_amlodipine: "He stopped amlodipine about a year ago because he felt well.",
    allergy_penicillin: "Penicillin caused an itchy rash; there was no breathing difficulty.",
    family_father_death: "His father died suddenly at 56, reportedly from a heart problem.",
    smoking: "He smokes about 20 cigarettes daily and has done so for 30 years.",
    alcohol: "He drinks two or three beers at weekends.",
    occupation: "He drives a passenger bus for a living.",
    wife_worried: "His wife noticed the episodes and strongly encouraged him to attend.",
    income_worry: "He cannot easily afford time off and worries about losing his income.",
    ice_ideas: "He thinks stress or indigestion may be causing the symptoms.",
    ice_concerns: "He fears dying suddenly as his father did and losing his driving licence.",
    ice_expectations: "He hopes for a tablet so he can return to work quickly.",
  },
  cards: [
    card({
      id: "opening_hand_hygiene",
      category: "opening",
      label: "Clean your hands before greeting the patient.",
      style: "closed",
      qualityTag: "professional opening",
      timeCostSec: 8,
      replies: {
        low: "He watches quietly.",
        mid: "He waits for you to sit down.",
        high: "He gives a small appreciative nod.",
      },
      satisfies: ["open_hand_hygiene"],
      rapportDelta: 2,
      examinerReaction: "nod",
    }),
    card({
      id: "opening_introduce",
      category: "opening",
      label: "Hello, I'm Sam, one of the medical students working with the clinic team.",
      style: "open",
      qualityTag: "clear introduction",
      timeCostSec: 12,
      replies: {
        low: "All right.",
        mid: "Hello, doctor.",
        high: "Hello. Thank you for seeing me.",
      },
      satisfies: ["open_introduce"],
      rapportDelta: 5,
      examinerReaction: "nod",
    }),
    card({
      id: "opening_confirm_identity",
      category: "opening",
      label: "Before we start, could I confirm your full name and date of birth?",
      style: "closed",
      qualityTag: "identity check",
      timeCostSec: 12,
      replies: {
        low: "Daniel Otieno. 14 June 1972.",
        mid: "Daniel Otieno, born 14 June 1972.",
        high: "Of course — Daniel Otieno, 14 June 1972.",
      },
      satisfies: ["open_identity"],
      rapportDelta: 2,
      examinerReaction: "nod",
    }),
    card({
      id: "opening_purpose_consent",
      category: "opening",
      label: "I'd like to ask about the tightness and your health generally. Is that okay?",
      style: "open",
      qualityTag: "purpose and consent",
      timeCostSec: 15,
      replies: {
        low: "Fine.",
        mid: "Yes, that's okay.",
        high: "Yes, please. I want to understand it.",
      },
      satisfies: ["open_purpose", "open_consent"],
      rapportDelta: 5,
      examinerReaction: "nod",
    }),
    card({
      id: "opening_comfort",
      category: "opening",
      label: "Are you comfortable talking here, or do you need anything before we begin?",
      style: "empathic",
      qualityTag: "patient comfort",
      timeCostSec: 8,
      replies: {
        low: "I'm fine.",
        mid: "I'm comfortable, thanks.",
        high: "I'm fine here, thank you for asking.",
      },
      satisfies: ["open_comfort", "comm_empathy"],
      rapportDelta: 4,
      examinerReaction: "impressed",
    }),
    card({
      id: "opening_assume_identity",
      category: "opening",
      label: "You're Daniel, and this is indigestion, right?",
      style: "leading",
      timeCostSec: 10,
      replies: {
        low: "I suppose so.",
        mid: "I'm Daniel, yes. I don't know what it is.",
        high: "Daniel, yes — but I'm not certain it's indigestion.",
      },
      penalises: ["open_identity", "comm_clear_technique"],
      rapportDelta: -7,
      examinerReaction: "eyebrow_raised",
    }),
    card({
      id: "opening_skip_basics",
      category: "opening",
      label: "Let's skip the formalities and get straight to your chest pain.",
      style: "dismissive",
      timeCostSec: 8,
      replies: {
        low: "Okay.",
        mid: "If you like.",
        high: "I thought you might need my details first.",
      },
      penalises: ["open_introduce", "open_identity", "open_consent", "comm_empathy"],
      rapportDelta: -10,
      examinerReaction: "slight_frown",
    }),

    card({
      id: "pc_open_story",
      category: "presenting_complaint",
      label: "Tell me what has been happening, in your own words.",
      style: "open",
      qualityTag: "open question",
      timeCostSec: 28,
      replies: {
        low: "My chest gets tight when I walk. It's probably indigestion.",
        mid: "For three weeks, I get a tight pressure in the middle of my chest on stairs. It settles when I stop.",
        high: "For about three weeks, stairs or a hill bring on a band-like pressure here in the middle. I get breathless and it settles after a few minutes' rest.",
      },
      revealsFacts: [
        "presenting_site",
        "presenting_onset_duration",
        "presenting_exertion",
        "presenting_relief",
      ],
      satisfies: ["hx_open_story", "hx_site", "hx_onset_duration", "hx_exacerbating_relief"],
      rapportDelta: 5,
      examinerReaction: "impressed",
      triggersCue: "cue_wife_worried",
    }),
    card({
      id: "pc_facilitate",
      category: "presenting_complaint",
      label: "Go on — take your time.",
      style: "facilitation",
      qualityTag: "facilitation",
      timeCostSec: 8,
      repeatable: true,
      unlockedBy: ["pc_open_story"],
      replies: {
        low: "It comes on with stairs.",
        mid: "I sometimes get short of breath with it.",
        high: "I get short of breath, and once I was sweaty. I have to stop until it passes.",
      },
      revealsFacts: ["associated_breathlessness", "associated_sweating"],
      satisfies: ["hx_facilitation", "hx_associated"],
      rapportDelta: 4,
      examinerReaction: "nod",
    }),
    card({
      id: "pc_site_closed",
      category: "presenting_complaint",
      label: "Where exactly do you feel the tightness?",
      style: "closed",
      timeCostSec: 12,
      replies: {
        low: "Here.",
        mid: "In the middle of my chest.",
        high: "Right in the centre, behind the breastbone.",
      },
      revealsFacts: ["presenting_site"],
      satisfies: ["hx_site"],
    }),
    card({
      id: "pc_onset_closed",
      category: "presenting_complaint",
      label: "When did this first start?",
      style: "closed",
      timeCostSec: 12,
      replies: {
        low: "A few weeks.",
        mid: "About three weeks ago.",
        high: "About three weeks ago; I hadn't had it before then.",
      },
      revealsFacts: ["presenting_onset_duration"],
      satisfies: ["hx_onset_duration"],
    }),
    card({
      id: "pc_previous_episodes",
      category: "presenting_complaint",
      label: "Had you ever felt anything like this before these three weeks?",
      style: "closed",
      timeCostSec: 12,
      replies: {
        low: "No.",
        mid: "No, this is new.",
        high: "No. It only started three weeks ago and seems a little easier to bring on now.",
      },
      revealsFacts: ["presenting_previous", "presenting_pattern"],
      satisfies: ["hx_pattern_previous"],
    }),
    card({
      id: "pc_leading_crushing",
      category: "presenting_complaint",
      label: "It's a crushing pain, isn't it?",
      style: "leading",
      timeCostSec: 14,
      replies: {
        low: "If you say so.",
        mid: "Not crushing, really. Tight.",
        high: "No — that's not quite it. It feels more like a tight band.",
      },
      revealsFacts: ["presenting_character"],
      penalises: ["comm_clear_technique"],
      rapportDelta: -5,
      examinerReaction: "eyebrow_raised",
    }),
    card({
      id: "pc_dismiss_indigestion",
      category: "presenting_complaint",
      label: "Are you sure it's not just indigestion?",
      style: "dismissive",
      timeCostSec: 14,
      replies: {
        low: "Maybe it is.",
        mid: "I don't know. That's why I'm here.",
        high: "I hoped so, but the antacids did nothing and my wife is worried.",
      },
      revealsFacts: ["self_treatment_antacids"],
      penalises: ["comm_empathy", "comm_clear_technique"],
      rapportDelta: -9,
      examinerReaction: "slight_frown",
    }),

    card({
      id: "symptom_open_detail",
      category: "history_of_symptom",
      label: "Talk me through a typical episode from the moment it starts until it settles.",
      style: "open",
      qualityTag: "open, focused question",
      timeCostSec: 32,
      unlockedBy: ["pc_open_story"],
      replies: {
        low: "I walk, it tightens, I stop, it goes.",
        mid: "On stairs it builds into a tight band, maybe six out of ten. I stop and it fades in a few minutes.",
        high: "Stairs or a hill bring on a central band-like pressure, about six out of ten, with breathlessness. I stop and within a few minutes it eases. Lately less effort seems to trigger it.",
      },
      revealsFacts: [
        "presenting_character",
        "presenting_exertion",
        "presenting_relief",
        "presenting_severity",
        "presenting_pattern",
        "associated_breathlessness",
      ],
      satisfies: [
        "hx_character",
        "hx_exacerbating_relief",
        "hx_severity",
        "hx_pattern_previous",
        "hx_associated",
      ],
      rapportDelta: 3,
      examinerReaction: "impressed",
    }),
    card({
      id: "symptom_radiation",
      category: "history_of_symptom",
      label: "Does the pressure travel anywhere, such as your arm, neck, jaw or back?",
      style: "closed",
      timeCostSec: 14,
      unlockedBy: ["pc_open_story"],
      replies: {
        low: "Sometimes my arm.",
        mid: "Sometimes into my left arm and jaw.",
        high: "Yes, once or twice it spread into my left arm and up to my jaw.",
      },
      revealsFacts: ["associated_radiation"],
      satisfies: ["hx_radiation"],
      examinerReaction: "nod",
    }),
    card({
      id: "symptom_associated",
      category: "history_of_symptom",
      label: "What else do you notice when the tightness happens?",
      style: "open",
      qualityTag: "open question",
      timeCostSec: 18,
      unlockedBy: ["pc_open_story"],
      replies: {
        low: "I get out of breath.",
        mid: "I get breathless, and once I felt sweaty.",
        high: "I'm short of breath with it and one time I broke into a sweat; no fainting or racing heart.",
      },
      revealsFacts: ["associated_breathlessness", "associated_sweating"],
      satisfies: ["hx_associated"],
      examinerReaction: "nod",
    }),
    card({
      id: "symptom_pain_at_rest",
      category: "history_of_symptom",
      label: "Has it ever happened while you were resting rather than exerting yourself?",
      style: "closed",
      timeCostSec: 16,
      unlockedBy: ["pc_open_story"],
      replies: {
        low: "Once.",
        mid: "Yes. Two days ago, sitting at home, for about fifteen minutes.",
        high: "Yes — two days ago while I was sitting at home. It was the same pressure and lasted around fifteen minutes. That frightened me.",
      },
      revealsFacts: ["red_flag_rest_pain"],
      satisfies: ["risk_pain_rest"],
      rapportDelta: 1,
      examinerReaction: "slight_frown",
    }),
    card({
      id: "symptom_syncope_palpitations",
      category: "history_of_symptom",
      label: "Have you fainted, felt close to fainting, or noticed your heart racing?",
      style: "closed",
      timeCostSec: 16,
      replies: {
        low: "No.",
        mid: "No fainting or racing heart.",
        high: "No, I've not fainted, felt light-headed or noticed palpitations.",
      },
      revealsFacts: ["no_syncope_palpitations"],
      satisfies: ["risk_syncope_palpitations"],
    }),
    card({
      id: "symptom_leading_pleuritic",
      category: "history_of_symptom",
      label: "It gets worse when you breathe in, doesn't it?",
      style: "leading",
      timeCostSec: 14,
      replies: {
        low: "No.",
        mid: "No, breathing doesn't change it.",
        high: "No. It isn't sharp and breathing in makes no difference.",
      },
      revealsFacts: ["presenting_not_pleuritic"],
      penalises: ["comm_clear_technique"],
      rapportDelta: -3,
      examinerReaction: "eyebrow_raised",
    }),
    card({
      id: "symptom_jargon",
      category: "history_of_symptom",
      label: "Any dyspnoea or diaphoresis with the episodes?",
      style: "jargon",
      timeCostSec: 16,
      replies: {
        low: "Any what?",
        mid: "I don't know those words.",
        high: "Do you mean breathlessness and sweating? Then yes.",
      },
      revealsFacts: ["associated_breathlessness", "associated_sweating"],
      penalises: ["comm_clear_technique"],
      rapportDelta: -5,
      examinerReaction: "eyebrow_raised",
    }),
    card({
      id: "symptom_irrelevant_infection",
      category: "history_of_symptom",
      label: "Have you had a recent tropical fever or insect bite?",
      style: "irrelevant",
      timeCostSec: 20,
      replies: {
        low: "No.",
        mid: "No, nothing like that.",
        high: "No. I haven't had a fever or insect bite.",
      },
      penalises: ["hx_open_story"],
      rapportDelta: -2,
      examinerReaction: "slight_frown",
    }),
    card({
      id: "symptom_multi_barrel",
      category: "history_of_symptom",
      label:
        "Is it sharp, burning, crushing, worse after food, worse breathing in, or tender to touch?",
      style: "multi_barrelled",
      timeCostSec: 24,
      replies: {
        low: "No… I don't think so.",
        mid: "That's a lot. It is tight, not sharp.",
        high: "One at a time, please. It feels tight, and food or breathing don't change it.",
      },
      revealsFacts: ["presenting_character", "presenting_not_food", "presenting_not_pleuritic"],
      penalises: ["comm_clear_technique"],
      rapportDelta: -6,
      examinerReaction: "slight_frown",
    }),

    card({
      id: "past_open_conditions",
      category: "past_and_drug_history",
      label: "Tell me about any medical conditions you have or have been treated for.",
      style: "open",
      qualityTag: "open question",
      timeCostSec: 24,
      replies: {
        low: "Blood pressure.",
        mid: "I was told I have high blood pressure. No diabetes that I know of.",
        high: "I was diagnosed with high blood pressure years ago. No diabetes, and I don't know my cholesterol result.",
      },
      revealsFacts: ["pmh_hypertension", "pmh_no_diabetes", "pmh_cholesterol_unknown"],
      satisfies: ["risk_hypertension", "risk_metabolic"],
      examinerReaction: "nod",
    }),
    card({
      id: "past_hypertension_closed",
      category: "past_and_drug_history",
      label: "Have you ever been diagnosed with high blood pressure?",
      style: "closed",
      timeCostSec: 12,
      replies: {
        low: "Yes.",
        mid: "Yes, years ago.",
        high: "Yes, several years ago, though I haven't kept up with treatment.",
      },
      revealsFacts: ["pmh_hypertension"],
      satisfies: ["risk_hypertension"],
    }),
    card({
      id: "past_metabolic_risk",
      category: "past_and_drug_history",
      label: "Have you had diabetes or high cholesterol diagnosed?",
      style: "closed",
      timeCostSec: 16,
      replies: {
        low: "No diabetes.",
        mid: "No diabetes. I don't know my cholesterol.",
        high: "I've never had diabetes; I can't remember anyone checking my cholesterol recently.",
      },
      revealsFacts: ["pmh_no_diabetes", "pmh_cholesterol_unknown"],
      satisfies: ["risk_metabolic"],
    }),
    card({
      id: "past_drugs_open",
      category: "past_and_drug_history",
      label: "What medicines do you take now, and have you stopped any prescribed medicines?",
      style: "open",
      qualityTag: "effective drug history",
      timeCostSec: 26,
      replies: {
        low: "Nothing regularly.",
        mid: "I stopped my amlodipine about a year ago because I felt fine. I tried antacids for this.",
        high: "I stopped amlodipine around a year ago because I felt well. Lately I've tried antacids and occasional ibuprofen, but neither helped much.",
      },
      revealsFacts: [
        "medication_stopped_amlodipine",
        "self_treatment_antacids",
        "self_treatment_ibuprofen",
      ],
      satisfies: ["risk_drugs"],
      rapportDelta: 1,
      examinerReaction: "impressed",
    }),
    card({
      id: "past_otc",
      category: "past_and_drug_history",
      label: "Have you tried anything from a pharmacy or taken painkillers for it?",
      style: "closed",
      timeCostSec: 15,
      replies: {
        low: "Antacids.",
        mid: "Antacids and sometimes ibuprofen. They didn't do much.",
        high: "I've used antacids and occasional ibuprofen, with very little effect.",
      },
      revealsFacts: ["self_treatment_antacids", "self_treatment_ibuprofen"],
      satisfies: ["risk_drugs"],
    }),
    card({
      id: "past_allergies",
      category: "past_and_drug_history",
      label: "Do you have any allergies, and what reaction do you get?",
      style: "closed",
      timeCostSec: 10,
      replies: {
        low: "Penicillin. Rash.",
        mid: "Penicillin gives me a rash.",
        high: "Penicillin caused an itchy rash. I didn't have trouble breathing.",
      },
      revealsFacts: ["allergy_penicillin"],
      satisfies: ["risk_allergies"],
    }),
    card({
      id: "past_multi_barrel",
      category: "past_and_drug_history",
      label: "Any blood pressure, diabetes, cholesterol, operations, tablets or allergies?",
      style: "multi_barrelled",
      timeCostSec: 24,
      replies: {
        low: "Blood pressure, I think.",
        mid: "Which one do you want me to answer?",
        high: "That's several things. I have high blood pressure and a penicillin allergy.",
      },
      revealsFacts: ["pmh_hypertension", "allergy_penicillin"],
      penalises: ["comm_clear_technique"],
      rapportDelta: -5,
      examinerReaction: "eyebrow_raised",
    }),
    card({
      id: "past_irrelevant_childhood",
      category: "past_and_drug_history",
      label: "Did you have chickenpox or measles as a child?",
      style: "irrelevant",
      timeCostSec: 20,
      replies: {
        low: "Probably.",
        mid: "I think so, but I can't remember.",
        high: "Probably, though I don't see how that relates to this.",
      },
      rapportDelta: -2,
      examinerReaction: "slight_frown",
    }),

    card({
      id: "social_family_history",
      category: "family_and_social",
      label: "Has anyone in your close family had heart disease or died suddenly at a young age?",
      style: "open",
      sensitive: true,
      earlyRapportPenalty: 7,
      timeCostSec: 22,
      replies: {
        low: "My father died.",
        mid: "My father died suddenly at 56. They said it was his heart.",
        high: "My father died suddenly from a heart problem at 56 — about my age. I try not to think about it.",
      },
      revealsFacts: ["family_father_death"],
      satisfies: ["risk_family"],
      rapportDelta: 1,
      examinerReaction: "nod",
      triggersCue: "cue_father_age",
    }),
    card({
      id: "social_smoking_neutral",
      category: "family_and_social",
      label: "Do you smoke now, or have you smoked in the past?",
      style: "closed",
      sensitive: true,
      earlyRapportPenalty: 5,
      timeCostSec: 18,
      replies: {
        low: "Yes.",
        mid: "About twenty a day.",
        high: "About twenty cigarettes a day for thirty years. I know it isn't good.",
      },
      revealsFacts: ["smoking"],
      satisfies: ["risk_smoking", "comm_clear_technique"],
      examinerReaction: "nod",
    }),
    card({
      id: "social_smoking_judgmental",
      category: "family_and_social",
      label: "You smoke, don't you? That's probably the cause.",
      style: "judgmental",
      sensitive: true,
      earlyRapportPenalty: 8,
      timeCostSec: 18,
      replies: {
        low: "Sometimes.",
        mid: "Yes, but you don't need to lecture me.",
        high: "I smoke, yes. I came for help, not to be blamed.",
      },
      revealsFacts: ["smoking"],
      penalises: ["comm_empathy", "comm_clear_technique"],
      rapportDelta: -12,
      examinerReaction: "slight_frown",
    }),
    card({
      id: "social_alcohol",
      category: "family_and_social",
      label: "How much alcohol would you drink in a typical week?",
      style: "open",
      sensitive: true,
      earlyRapportPenalty: 4,
      timeCostSec: 12,
      replies: {
        low: "A few beers.",
        mid: "Two or three beers at weekends.",
        high: "Usually two or three beers over the weekend, nothing most weekdays.",
      },
      revealsFacts: ["alcohol"],
      satisfies: ["risk_alcohol"],
    }),
    card({
      id: "social_occupation",
      category: "family_and_social",
      label: "What work do you do, and how are these symptoms affecting it?",
      style: "open",
      timeCostSec: 16,
      replies: {
        low: "Bus driver. I'm managing.",
        mid: "I drive a bus. I can work, but stairs at the depot set it off.",
        high: "I'm a passenger-bus driver. I'm still working, but I'm scared this could affect my licence and livelihood.",
      },
      revealsFacts: ["occupation", "income_worry"],
      satisfies: ["risk_occupation"],
      rapportDelta: 2,
      examinerReaction: "nod",
    }),
    card({
      id: "social_work_impact",
      category: "family_and_social",
      label: "What would time off or further appointments mean for you?",
      style: "empathic",
      sensitive: true,
      earlyRapportPenalty: 4,
      timeCostSec: 18,
      replies: {
        low: "I need to work.",
        mid: "I can't really afford time off.",
        high: "If I stop driving, we lose most of our income. I can't really afford time off work.",
      },
      revealsFacts: ["income_worry"],
      rapportDelta: 4,
      examinerReaction: "impressed",
      triggersCue: "cue_income",
    }),
    card({
      id: "social_multi_barrel",
      category: "family_and_social",
      label: "Do you smoke, drink, exercise, eat well, use drugs and have stress at home?",
      style: "multi_barrelled",
      sensitive: true,
      earlyRapportPenalty: 8,
      timeCostSec: 28,
      replies: {
        low: "Some of those.",
        mid: "That's a lot of questions.",
        high: "Could we take those one at a time?",
      },
      penalises: ["comm_clear_technique"],
      rapportDelta: -7,
      examinerReaction: "eyebrow_raised",
    }),
    card({
      id: "social_judgment_income",
      category: "family_and_social",
      label: "Surely your health matters more than missing a day's wages?",
      style: "judgmental",
      sensitive: true,
      earlyRapportPenalty: 8,
      timeCostSec: 18,
      replies: {
        low: "It's not that simple.",
        mid: "You don't know my bills.",
        high: "My family depends on my income. Please don't make it sound simple.",
      },
      revealsFacts: ["income_worry"],
      penalises: ["comm_empathy", "comm_clear_technique"],
      rapportDelta: -12,
      examinerReaction: "slight_frown",
    }),

    card({
      id: "comm_empathy",
      category: "communicate",
      label: "That sounds worrying. Thank you for telling me.",
      style: "empathic",
      qualityTag: "empathy",
      timeCostSec: 10,
      repeatable: true,
      replies: {
        low: "Mm.",
        mid: "It has been on my mind.",
        high: "Thank you. I've been trying not to show how worried I am.",
      },
      satisfies: ["comm_empathy"],
      rapportDelta: 8,
      examinerReaction: "impressed",
    }),
    card({
      id: "comm_ideas",
      category: "communicate",
      label: "What do you think might be causing the tightness?",
      style: "open",
      qualityTag: "ideas",
      timeCostSec: 14,
      replies: {
        low: "Indigestion.",
        mid: "Maybe indigestion or stress.",
        high: "I've told myself it is stress or indigestion, though part of me isn't convinced.",
      },
      revealsFacts: ["ice_ideas"],
      satisfies: ["ice_ideas"],
      rapportDelta: 2,
      examinerReaction: "nod",
    }),
    card({
      id: "comm_concerns",
      category: "communicate",
      label: "What is your biggest worry about what this could mean?",
      style: "empathic",
      qualityTag: "concerns",
      timeCostSec: 16,
      replies: {
        low: "I don't know. I'd rather not say.",
        mid: "My father died suddenly at my age. I worry the same will happen — and that I'll lose my licence.",
        high: "I'm frightened it is my heart and I'll die like my father. If I lose my bus licence, my family also loses its income.",
      },
      conditionalFactReveal: {
        minimumRapportBand: "mid",
        factIds: ["ice_concerns", "family_father_death", "income_worry"],
      },
      satisfies: ["ice_concerns"],
      rapportDelta: 5,
      examinerReaction: "impressed",
      triggersCurveball: true,
    }),
    card({
      id: "comm_expectations",
      category: "communicate",
      label: "What were you hoping we could do for you today?",
      style: "open",
      qualityTag: "expectations",
      timeCostSec: 14,
      replies: {
        low: "Give me something.",
        mid: "Maybe a tablet so I can get back to work.",
        high: "I hoped there might be a tablet, but I also need to know whether it is safe for me to keep driving.",
      },
      revealsFacts: ["ice_expectations"],
      satisfies: ["ice_expectations"],
      rapportDelta: 2,
      examinerReaction: "nod",
    }),
    card({
      id: "cue_wife_pickup",
      category: "communicate",
      label: "You mentioned your wife is worried. What has she noticed?",
      style: "facilitation",
      qualityTag: "picks up a cue",
      timeCostSec: 12,
      availableOnlyInWindowOfCue: "cue_wife_worried",
      replies: {
        low: "She saw me stop on the stairs.",
        mid: "She noticed I keep stopping on stairs and made me come.",
        high: "She saw me clutch my chest and stop on the stairs. She was frightened and insisted I come.",
      },
      revealsFacts: ["wife_worried", "presenting_exertion"],
      satisfies: ["comm_cue_wife"],
      rapportDelta: 7,
      examinerReaction: "impressed",
    }),
    card({
      id: "cue_father_pickup",
      category: "communicate",
      label:
        "You paused when you mentioned your father. Would you like to tell me what worries you about that?",
      style: "empathic",
      qualityTag: "picks up a cue",
      timeCostSec: 14,
      sensitive: true,
      earlyRapportPenalty: 4,
      availableOnlyInWindowOfCue: "cue_father_age",
      replies: {
        low: "Not really.",
        mid: "He died suddenly at 56. I'm afraid I'm next.",
        high: "He died suddenly at 56 from his heart. I'm almost that age, and I'm scared the same thing is happening to me.",
      },
      revealsFacts: ["family_father_death"],
      conditionalFactReveal: { minimumRapportBand: "mid", factIds: ["ice_concerns"] },
      satisfies: ["comm_cue_father", "comm_empathy"],
      rapportDelta: 10,
      examinerReaction: "impressed",
    }),
    card({
      id: "cue_income_pickup",
      category: "communicate",
      label:
        "It sounds as though time off could put real pressure on your family. Can you tell me more?",
      style: "empathic",
      qualityTag: "picks up a cue",
      timeCostSec: 12,
      sensitive: true,
      earlyRapportPenalty: 4,
      availableOnlyInWindowOfCue: "cue_income",
      replies: {
        low: "We need the money.",
        mid: "I'm the main earner, so time off is difficult.",
        high: "I'm the main earner. Losing work or my licence would hit the whole family, though I also want to be safe.",
      },
      revealsFacts: ["income_worry"],
      satisfies: ["comm_cue_income", "comm_empathy"],
      rapportDelta: 9,
      examinerReaction: "impressed",
    }),
    card({
      id: "curve_false_reassurance",
      category: "communicate",
      label: "I'm sure it's nothing to worry about.",
      style: "dismissive",
      timeCostSec: 12,
      unlockedBy: ["comm_concerns"],
      replies: {
        low: "Are you sure?",
        mid: "How can you be sure without tests?",
        high: "That doesn't sound honest. You haven't checked yet.",
      },
      penalises: ["comm_curveball", "comm_empathy", "closing_next_step"],
      rapportDelta: -25,
      examinerReaction: "slight_frown",
      curveballResponseKind: "false_reassurance",
    }),
    card({
      id: "curve_evasive",
      category: "communicate",
      label: "I can't say anything about that yet.",
      style: "dismissive",
      timeCostSec: 12,
      unlockedBy: ["comm_concerns"],
      replies: {
        low: "Right.",
        mid: "That doesn't help much.",
        high: "I understand you need tests, but could you at least explain the concern?",
      },
      penalises: ["comm_curveball", "comm_empathy"],
      rapportDelta: -10,
      examinerReaction: "eyebrow_raised",
      curveballResponseKind: "evasive",
    }),
    card({
      id: "curve_deflect",
      category: "communicate",
      label: "The consultant will explain that to you later.",
      style: "dismissive",
      timeCostSec: 12,
      unlockedBy: ["comm_concerns"],
      replies: {
        low: "Okay.",
        mid: "But I'm asking you now.",
        high: "I know the consultant will review me, but I need an honest answer from you.",
      },
      penalises: ["comm_curveball", "comm_empathy"],
      rapportDelta: -12,
      examinerReaction: "slight_frown",
      curveballResponseKind: "deflecting",
    }),
    card({
      id: "curve_honest_empathic",
      category: "communicate",
      label:
        "I can see why you're worried. It could be related to your heart, so we'll arrange tests today. Can I explain what happens next?",
      style: "empathic",
      qualityTag: "honest and empathic",
      timeCostSec: 18,
      unlockedBy: ["comm_concerns"],
      replies: {
        low: "All right. Tell me.",
        mid: "Thank you for being straight with me. Yes, please explain.",
        high: "That is frightening, but I appreciate your honesty. Please tell me what happens now.",
      },
      satisfies: ["comm_curveball", "comm_empathy", "closing_next_step"],
      rapportDelta: 12,
      examinerReaction: "impressed",
      curveballResponseKind: "honest_empathic",
    }),

    card({
      id: "closing_summary",
      category: "closing",
      label: "Let me summarise what I've understood, then you can correct me.",
      style: "open",
      qualityTag: "summary",
      timeCostSec: 24,
      replies: {
        low: "Okay.",
        mid: "Yes, that's right.",
        high: "Yes, you've understood it. The episode at rest and my father's death are what worry me most.",
      },
      satisfies: ["closing_summary"],
      rapportDelta: 5,
      examinerReaction: "impressed",
    }),
    card({
      id: "closing_anything_missed",
      category: "closing",
      label: "Is there anything important I haven't asked, or anything you'd like to add?",
      style: "open",
      timeCostSec: 12,
      replies: {
        low: "No.",
        mid: "No, I think that's it.",
        high: "Only that I need to know what this means for driving and work.",
      },
      satisfies: ["closing_missed"],
      rapportDelta: 3,
      examinerReaction: "nod",
    }),
    card({
      id: "closing_thank",
      category: "closing",
      label: "Thank you for answering my questions, Mr Otieno.",
      style: "empathic",
      timeCostSec: 8,
      replies: { low: "Okay.", mid: "Thank you.", high: "Thank you for listening." },
      satisfies: ["closing_thank"],
      rapportDelta: 3,
      examinerReaction: "nod",
    }),
    card({
      id: "closing_plain_next_step",
      category: "closing",
      label:
        "Because this may be heart-related, I need to discuss you urgently with the clinical team today. We'll check your heart tracing and blood tests, and you should not drive until assessed.",
      style: "empathic",
      qualityTag: "clear safety-netting",
      timeCostSec: 18,
      replies: {
        low: "Today? All right.",
        mid: "I understand. I'm worried about driving, but I see why.",
        high: "Thank you for explaining it plainly. I'll wait for the team and won't drive.",
      },
      satisfies: ["closing_next_step"],
      rapportDelta: 6,
      examinerReaction: "impressed",
    }),
    card({
      id: "closing_abrupt",
      category: "closing",
      label: "That's all I need. You can wait outside.",
      style: "dismissive",
      timeCostSec: 8,
      replies: {
        low: "Fine.",
        mid: "But what happens now?",
        high: "Please don't leave me without explaining whether this is serious.",
      },
      penalises: ["closing_missed", "closing_thank", "closing_next_step", "comm_empathy"],
      rapportDelta: -12,
      examinerReaction: "slight_frown",
    }),
    card({
      id: "closing_jargon_plan",
      category: "closing",
      label: "We'll exclude ACS with serial hs-cTn and risk-stratify before disposition.",
      style: "jargon",
      timeCostSec: 16,
      replies: {
        low: "I don't understand.",
        mid: "What does any of that mean?",
        high: "Could you explain that without the abbreviations?",
      },
      penalises: ["closing_next_step", "comm_clear_technique"],
      rapportDelta: -7,
      examinerReaction: "eyebrow_raised",
    }),
    card({
      id: "closing_multi_safety",
      category: "closing",
      label:
        "You'll need an ECG, bloods, review, no driving, medication changes and follow-up — any questions?",
      style: "multi_barrelled",
      timeCostSec: 20,
      replies: {
        low: "What?",
        mid: "That was a lot. Am I staying here?",
        high: "Could you slow down and explain what happens first?",
      },
      penalises: ["closing_next_step", "comm_clear_technique"],
      rapportDelta: -6,
      examinerReaction: "slight_frown",
    }),
  ],
  cues: [
    {
      id: "cue_wife_worried",
      type: "informational",
      patientLine: "My wife made me come. She's worried.",
      pickupCardIds: ["cue_wife_pickup"],
      idealResponseCardId: "cue_wife_pickup",
      minimumRapportBand: "low",
      requiresCardIds: [],
      windowActions: 3,
      missedRapportPenalty: 5,
    },
    {
      id: "cue_father_age",
      type: "emotional",
      patientLine: "My father was around my age when… well, never mind.",
      pickupCardIds: ["cue_father_pickup"],
      idealResponseCardId: "cue_father_pickup",
      minimumRapportBand: "mid",
      requiresCardIds: ["symptom_open_detail"],
      windowActions: 3,
      missedRapportPenalty: 9,
    },
    {
      id: "cue_income",
      type: "emotional",
      patientLine: "I can't really afford time off work.",
      pickupCardIds: ["cue_income_pickup"],
      idealResponseCardId: "cue_income_pickup",
      minimumRapportBand: "mid",
      requiresCardIds: [],
      windowActions: 3,
      missedRapportPenalty: 7,
    },
  ],
  curveball: {
    triggerAtPercentClock: 60,
    patientLine: "Be straight with me, doctor. Is it my heart?",
    responseCardIds: [
      "curve_false_reassurance",
      "curve_evasive",
      "curve_deflect",
      "curve_honest_empathic",
    ],
    criticalFailCardIds: ["curve_false_reassurance"],
  },
  checklist: [
    {
      id: "open_hand_hygiene",
      domain: "opening_and_consent",
      label: "Performed hand hygiene",
      weight: 1,
      criticalFailIfMissing: false,
      coachingLine: "Make hand hygiene part of your automatic entrance routine.",
    },
    {
      id: "open_introduce",
      domain: "opening_and_consent",
      label: "Introduced self with name and role",
      weight: 2,
      criticalFailIfMissing: true,
      coachingLine: "State both your name and role before beginning the history.",
    },
    {
      id: "open_identity",
      domain: "opening_and_consent",
      label: "Confirmed patient name and date of birth",
      weight: 2,
      criticalFailIfMissing: true,
      coachingLine: "Use two identifiers before discussing clinical details.",
    },
    {
      id: "open_purpose",
      domain: "opening_and_consent",
      label: "Explained the purpose of the conversation",
      weight: 1,
      criticalFailIfMissing: false,
      coachingLine: "Briefly frame what you would like to discuss.",
    },
    {
      id: "open_consent",
      domain: "opening_and_consent",
      label: "Gained consent to proceed",
      weight: 2,
      criticalFailIfMissing: true,
      coachingLine: "Ask permission rather than assuming the patient is ready.",
    },
    {
      id: "open_comfort",
      domain: "opening_and_consent",
      label: "Checked privacy and comfort",
      weight: 1,
      criticalFailIfMissing: false,
      coachingLine: "A quick comfort check builds safety without using much time.",
    },

    {
      id: "hx_open_story",
      domain: "history_content",
      label: "Opened with the patient's account",
      weight: 2,
      criticalFailIfMissing: false,
      coachingLine: "Begin broadly so the patient can give a useful symptom narrative.",
    },
    {
      id: "hx_facilitation",
      domain: "history_content",
      label: "Used facilitation without interrupting",
      weight: 1,
      criticalFailIfMissing: false,
      coachingLine: "A short ‘go on’ can uncover more than a string of closed questions.",
    },
    {
      id: "hx_site",
      domain: "history_content",
      label: "Established the site",
      weight: 1,
      criticalFailIfMissing: false,
      coachingLine: "Clarify exactly where the symptom is felt.",
    },
    {
      id: "hx_onset_duration",
      domain: "history_content",
      label: "Established onset and duration",
      weight: 2,
      criticalFailIfMissing: false,
      coachingLine: "Anchor the symptom in time and ask when it first began.",
    },
    {
      id: "hx_character",
      domain: "history_content",
      label: "Clarified the character",
      weight: 2,
      criticalFailIfMissing: false,
      coachingLine: "Let the patient describe the sensation before offering adjectives.",
    },
    {
      id: "hx_radiation",
      domain: "history_content",
      label: "Asked about radiation",
      weight: 2,
      criticalFailIfMissing: false,
      coachingLine:
        "For chest discomfort, ask specifically about arm, jaw, neck and back radiation.",
    },
    {
      id: "hx_associated",
      domain: "history_content",
      label: "Explored associated symptoms",
      weight: 2,
      criticalFailIfMissing: false,
      coachingLine: "Use an open associated-symptom question before focused screening.",
    },
    {
      id: "hx_exacerbating_relief",
      domain: "history_content",
      label: "Identified exertional trigger and relief with rest",
      weight: 3,
      criticalFailIfMissing: false,
      coachingLine: "Exertion and relief with rest are high-yield discriminators in this history.",
    },
    {
      id: "hx_severity",
      domain: "history_content",
      label: "Assessed severity and functional impact",
      weight: 1,
      criticalFailIfMissing: false,
      coachingLine: "Link severity to what the symptom makes the patient stop doing.",
    },
    {
      id: "hx_pattern_previous",
      domain: "history_content",
      label: "Clarified pattern, progression and previous episodes",
      weight: 2,
      criticalFailIfMissing: false,
      coachingLine: "Ask whether episodes are changing and whether this has happened before.",
    },

    {
      id: "risk_pain_rest",
      domain: "risk_and_red_flags",
      label: "Screened for pain at rest",
      weight: 5,
      criticalFailIfMissing: true,
      coachingLine: "Always ask whether exertional chest discomfort has also occurred at rest.",
    },
    {
      id: "risk_syncope_palpitations",
      domain: "risk_and_red_flags",
      label: "Asked about syncope and palpitations",
      weight: 2,
      criticalFailIfMissing: false,
      coachingLine:
        "Screen for fainting, presyncope and palpitations when assessing chest symptoms.",
    },
    {
      id: "risk_hypertension",
      domain: "risk_and_red_flags",
      label: "Identified hypertension",
      weight: 2,
      criticalFailIfMissing: false,
      coachingLine: "Actively establish vascular risk factors, including hypertension.",
    },
    {
      id: "risk_metabolic",
      domain: "risk_and_red_flags",
      label: "Asked about diabetes and cholesterol",
      weight: 2,
      criticalFailIfMissing: false,
      coachingLine: "Include diabetes and lipid history in cardiovascular risk assessment.",
    },
    {
      id: "risk_smoking",
      domain: "risk_and_red_flags",
      label: "Quantified smoking non-judgmentally",
      weight: 3,
      criticalFailIfMissing: false,
      coachingLine: "Ask neutrally, then quantify cigarettes per day and duration.",
    },
    {
      id: "risk_family",
      domain: "risk_and_red_flags",
      label: "Asked about premature family heart disease",
      weight: 3,
      criticalFailIfMissing: false,
      coachingLine: "Ask about early cardiac disease and sudden death in close relatives.",
    },
    {
      id: "risk_drugs",
      domain: "risk_and_red_flags",
      label: "Covered prescribed, stopped and over-the-counter medicines",
      weight: 3,
      criticalFailIfMissing: false,
      coachingLine:
        "Ask what was stopped as well as what is currently taken, including pharmacy medicines.",
    },
    {
      id: "risk_allergies",
      domain: "risk_and_red_flags",
      label: "Asked about allergies and reaction",
      weight: 1,
      criticalFailIfMissing: false,
      coachingLine: "Record both the allergen and the nature of the reaction.",
    },
    {
      id: "risk_alcohol",
      domain: "risk_and_red_flags",
      label: "Quantified alcohol use",
      weight: 1,
      criticalFailIfMissing: false,
      coachingLine: "Use a neutral, typical-week question to quantify alcohol.",
    },
    {
      id: "risk_occupation",
      domain: "risk_and_red_flags",
      label: "Established occupation and safety implications",
      weight: 3,
      criticalFailIfMissing: false,
      coachingLine: "Occupation matters here because symptoms may make passenger driving unsafe.",
    },

    {
      id: "ice_ideas",
      domain: "ice",
      label: "Explored the patient's ideas",
      weight: 2,
      criticalFailIfMissing: false,
      coachingLine: "Ask what the patient thinks may be causing the symptom.",
    },
    {
      id: "ice_concerns",
      domain: "ice",
      label: "Explored the patient's concerns",
      weight: 3,
      criticalFailIfMissing: false,
      coachingLine: "Ask directly about the biggest worry once enough rapport is established.",
    },
    {
      id: "ice_expectations",
      domain: "ice",
      label: "Explored the patient's expectations",
      weight: 2,
      criticalFailIfMissing: false,
      coachingLine: "Find out what the patient hopes will happen today.",
    },

    {
      id: "comm_cue_wife",
      domain: "communication",
      label: "Picked up the wife's-worry cue",
      weight: 2,
      criticalFailIfMissing: false,
      coachingLine: "When a relative's concern is mentioned, ask what they observed.",
    },
    {
      id: "comm_cue_father",
      domain: "communication",
      label: "Picked up the father's-age cue",
      weight: 3,
      criticalFailIfMissing: false,
      coachingLine: "A pause or unfinished sentence often carries the patient's main fear.",
    },
    {
      id: "comm_cue_income",
      domain: "communication",
      label: "Picked up the income cue",
      weight: 2,
      criticalFailIfMissing: false,
      coachingLine: "Acknowledge practical worries rather than treating them as a distraction.",
    },
    {
      id: "comm_empathy",
      domain: "communication",
      label: "Responded empathically",
      weight: 3,
      criticalFailIfMissing: false,
      coachingLine: "Name or validate the emotion before returning to factual questions.",
    },
    {
      id: "comm_clear_technique",
      domain: "communication",
      label: "Used clear, non-leading and non-judgmental language",
      weight: 3,
      criticalFailIfMissing: false,
      coachingLine: "Prefer one plain, neutral question at a time.",
    },
    {
      id: "comm_curveball",
      domain: "communication",
      label: "Handled the heart-question honestly and empathically",
      weight: 4,
      criticalFailIfMissing: false,
      coachingLine: "Acknowledge uncertainty and concern, then explain the safe immediate plan.",
    },

    {
      id: "closing_summary",
      domain: "closing_and_safety",
      label: "Summarised the key history",
      weight: 3,
      criticalFailIfMissing: false,
      coachingLine: "Use a focused summary to confirm the red flag and risk profile.",
    },
    {
      id: "closing_missed",
      domain: "closing_and_safety",
      label: "Asked whether anything was missed",
      weight: 1,
      criticalFailIfMissing: false,
      coachingLine: "Give the patient one final chance to add or correct information.",
    },
    {
      id: "closing_thank",
      domain: "closing_and_safety",
      label: "Thanked the patient",
      weight: 1,
      criticalFailIfMissing: false,
      coachingLine: "Close by acknowledging the patient's time and disclosure.",
    },
    {
      id: "closing_next_step",
      domain: "closing_and_safety",
      label: "Explained an urgent next step in plain language",
      weight: 4,
      criticalFailIfMissing: false,
      coachingLine: "State the immediate escalation, tests and driving advice without jargon.",
    },
  ],
  criticalFails: [
    {
      id: "critical_opening_safety",
      label: "Omitted introduction, identity check or consent",
      trigger: "missing_any_checklist",
      triggeredBy: ["open_introduce", "open_identity", "open_consent"],
    },
    {
      id: "critical_false_reassurance",
      label: "Gave false reassurance about possible cardiac pain",
      trigger: "action",
      triggeredBy: ["curve_false_reassurance"],
    },
    {
      id: "critical_missed_rest_pain",
      label: "Did not screen for chest pain at rest",
      trigger: "missing_any_checklist",
      triggeredBy: ["risk_pain_rest"],
    },
  ],
  examinerQuestions: [
    {
      id: "exam_differential",
      prompt:
        "Which diagnoses are most important to consider from this history? Select all that apply.",
      type: "multi",
      options: [
        {
          id: "stable_angina",
          text: "Chronic coronary syndrome (stable angina pattern)",
          correct: true,
        },
        {
          id: "unstable_angina",
          text: "Acute coronary syndrome / unstable angina because symptoms occurred at rest",
          correct: true,
        },
        {
          id: "gord",
          text: "Gastro-oesophageal reflux disease as the leading explanation",
          correct: false,
        },
        {
          id: "pulmonary_embolism",
          text: "Pulmonary embolism as the leading explanation",
          correct: false,
        },
        {
          id: "musculoskeletal",
          text: "Musculoskeletal chest wall pain as the leading explanation",
          correct: false,
        },
      ],
      explanation:
        "The reproducible exertional pressure relieved by rest is typical of myocardial ischaemia, while the recent 15-minute episode at rest is an unstable feature requiring urgent assessment for acute coronary syndrome.",
    },
    {
      id: "exam_investigations",
      prompt:
        "Which immediate assessments or investigations are appropriate today? Select all that apply.",
      type: "multi",
      options: [
        { id: "ecg", text: "12-lead ECG", correct: true },
        {
          id: "troponin",
          text: "High-sensitivity cardiac troponin using the local serial pathway",
          correct: true,
        },
        {
          id: "observations",
          text: "Immediate observations, including blood pressure and oxygen saturation",
          correct: true,
        },
        {
          id: "exercise_ecg",
          text: "Send him directly for an exercise ECG before clinical review",
          correct: false,
        },
        {
          id: "d_dimer",
          text: "D-dimer as the first-line test regardless of clinical probability",
          correct: false,
        },
        { id: "endoscopy", text: "Urgent upper gastrointestinal endoscopy", correct: false },
      ],
      explanation:
        "Possible acute coronary syndrome needs urgent clinical assessment, observations, a 12-lead ECG and high-sensitivity troponin testing according to the local serial protocol. Exercise testing is not the immediate step when unstable symptoms are possible.",
    },
    {
      id: "exam_driving",
      prompt: "What is the most important immediate safety consideration related to his job?",
      type: "single",
      options: [
        {
          id: "stop_driving",
          text: "He should stop passenger-bus driving pending urgent assessment and follow local licensing and occupational advice",
          correct: true,
        },
        {
          id: "drive_if_pain_free",
          text: "He may continue driving as long as he has no pain when starting the shift",
          correct: false,
        },
        {
          id: "night_only",
          text: "He should drive only at night when traffic is lighter",
          correct: false,
        },
        {
          id: "antacid_first",
          text: "He may drive after taking an antacid before each shift",
          correct: false,
        },
      ],
      explanation:
        "Recurrent exertional symptoms with an episode at rest could cause sudden incapacity. He should not drive a passenger vehicle until urgently assessed, and definitive restrictions should follow the applicable local licensing and occupational rules.",
    },
  ],
  modelRun: [
    { cardId: "opening_hand_hygiene", reason: "Begin with visible infection-control practice." },
    { cardId: "opening_introduce", reason: "Establish name and clinical role." },
    { cardId: "opening_confirm_identity", reason: "Use two patient identifiers." },
    {
      cardId: "opening_purpose_consent",
      reason: "Frame the focused history and obtain permission efficiently.",
    },
    { cardId: "opening_comfort", reason: "Build rapport before sensitive questions." },
    {
      cardId: "pc_open_story",
      reason: "Let one open question establish the main exertional pattern.",
    },
    {
      cardId: "cue_wife_pickup",
      reason: "Pick up the early informational cue before its window closes.",
    },
    { cardId: "pc_facilitate", reason: "Encourage volunteered associated symptoms." },
    {
      cardId: "symptom_open_detail",
      reason: "Efficiently cover character, severity, triggers, relief and progression.",
    },
    { cardId: "symptom_radiation", reason: "Ask specifically about high-yield radiation." },
    { cardId: "symptom_pain_at_rest", reason: "Find the buried unstable red flag." },
    {
      cardId: "symptom_syncope_palpitations",
      reason: "Complete a focused cardiovascular red-flag screen.",
    },
    {
      cardId: "past_open_conditions",
      reason: "Cover major vascular risk factors with one open question.",
    },
    { cardId: "past_drugs_open", reason: "Reveal stopped antihypertensive and self-treatment." },
    { cardId: "past_allergies", reason: "Document the allergen and reaction." },
    { cardId: "social_family_history", reason: "Identify premature sudden cardiac death." },
    { cardId: "cue_father_pickup", reason: "Respond to the emotional cue rather than moving on." },
    { cardId: "social_smoking_neutral", reason: "Quantify smoking without blame." },
    { cardId: "social_occupation", reason: "Identify the passenger-driving safety consequence." },
    {
      cardId: "social_work_impact",
      reason: "Explore the practical worry and invite the income cue.",
    },
    { cardId: "cue_income_pickup", reason: "Acknowledge the patient's livelihood concern." },
    { cardId: "comm_ideas", reason: "Explore the patient's explanatory model." },
    { cardId: "comm_concerns", reason: "Reveal the hidden worry once rapport is established." },
    {
      cardId: "curve_honest_empathic",
      reason: "Answer uncertainty honestly and explain urgent assessment.",
    },
    { cardId: "comm_expectations", reason: "Clarify what the patient hopes to receive today." },
    { cardId: "closing_summary", reason: "Confirm the key pattern, red flag and risks." },
    {
      cardId: "closing_plain_next_step",
      reason: "End with urgent escalation and driving advice in plain language.",
    },
  ],
  nudges: [
    {
      tier: 1,
      pointCost: 2,
      text: "What feature would make apparently predictable exertional symptoms less stable?",
    },
    {
      tier: 2,
      pointCost: 5,
      text: "Think about what happens outside exertion, and what the patient nearly said but did not finish.",
    },
    {
      tier: 3,
      pointCost: 9,
      text: "Which focused question separates symptoms only on activity from symptoms that can also occur when sitting still?",
    },
  ],
  ratingThresholds: {
    borderline: 45,
    pass: 58,
    good: 72,
    excellent: 86,
    criticalFailCap: "clear_fail",
    componentWeights: {
      checklist: 0.6,
      communication: 0.15,
      timeManagement: 0.1,
      examinerQuestions: 0.15,
    },
    communicationCaps: {
      borderlineIfRapportBelow: 35,
      borderlineIfCommunicationBelow: 40,
    },
  },
  idleDrift: {
    startsAfterRealSeconds: 20,
    realSecondsPerSimulatedSecond: 2,
    pausedInLearn: true,
  },
};
