import { useEffect, useMemo, useState } from "react";
import { Link } from "@tanstack/react-router";
import { Activity, ArrowLeft, ArrowRight, Bell, BookOpen, Brain, ChevronDown, ChevronRight, CircleCheck, Clock3, Flame, HeartPulse, Home, Layers3, Medal, Plus, Sparkles, Stethoscope, Target, Trophy, Users, X } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import heartImage from "@/assets/clinical-heart.jpg";
import type { Database } from "@/integrations/supabase/types";

type Student = Pick<Database["public"]["Tables"]["students"]["Row"], "id" | "name" | "university" | "country" | "year_of_study" | "medical_program" | "current_level" | "subjects_studying" | "current_rotation" | "specialty_interests" | "weak_areas" | "study_goal" | "daily_study_target_minutes" | "notification_prefs" | "xp" | "level" | "streak_days" | "longest_streak" | "created_at">;
type View = "home" | "cases" | "practice" | "groups" | "profile";
type PracticeTab = "OSCE" | "Quizzes" | "Flashcards";
const columns = "id,name,university,country,year_of_study,medical_program,current_level,subjects_studying,current_rotation,specialty_interests,weak_areas,study_goal,daily_study_target_minutes,notification_prefs,xp,level,streak_days,longest_streak,created_at";
const nav = [{ label: "Home", to: "/", icon: Home }, { label: "Cases", to: "/cases", icon: HeartPulse }, { label: "Practice", to: "/practice", icon: Stethoscope }, { label: "Groups", to: "/groups", icon: Users }, { label: "Profile", to: "/profile", icon: Activity }] as const;
const subjects = ["Anatomy", "Biochemistry", "Clinical Skills", "Internal Medicine", "Microbiology", "Obstetrics & Gynaecology", "Paediatrics", "Pathology", "Pharmacology", "Physiology", "Public Health", "Surgery"];
const initials = (name: string) => name.split(" ").map(part => part[0]).slice(0, 2).join("").toUpperCase();
const firstName = (name?: string) => name?.split(" ")[0] ?? "student";

function IconBubble({ icon: Icon, color = "lavender" }: { icon: typeof Home; color?: string }) {
  return <span className={`flex size-11 shrink-0 items-center justify-center rounded-2xl bg-${color}-soft text-foreground shadow-[inset_0_2px_1px_var(--card)]`}><Icon size={21} strokeWidth={2.2} /></span>;
}
function SectionHeading({ title, action, to }: { title: string; action?: string; to?: "/cases" | "/practice" | "/groups" }) {
  return <div className="mb-4 flex items-center justify-between gap-3"><h2 className="font-display text-xl font-black md:text-2xl">{title}</h2>{action && to && <Link to={to} className="flex items-center gap-1 text-sm font-extrabold text-ink-soft hover:text-foreground">{action}<ChevronRight size={16}/></Link>}</div>;
}
function EmptyAction({ label }: { label: string }) { return <p className="mt-2 text-sm leading-relaxed text-muted-foreground">{label}</p>; }

export function StudyApp({ view }: { view: View }) {
  const [students, setStudents] = useState<Student[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [switcherOpen, setSwitcherOpen] = useState(false);
  const [onboarding, setOnboarding] = useState(false);
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState("");
  const [practiceTab, setPracticeTab] = useState<PracticeTab>("OSCE");
  const [activity, setActivity] = useState<string | null>(null);
  const student = useMemo(() => students.find(item => item.id === selectedId) ?? students[0], [students, selectedId]);

  useEffect(() => {
    let active = true;
    supabase.from("students").select(columns).order("created_at", { ascending: true }).then(({ data, error }) => {
      if (!active) return;
      if (error) setLoadError("Student profiles couldn't be loaded. Please refresh to try again.");
      else setStudents((data ?? []) as Student[]);
      const saved = window.localStorage.getItem("medley-demo-student");
      if (saved) setSelectedId(saved);
      setLoading(false);
    });
    return () => { active = false; };
  }, []);
  const selectStudent = (id: string) => { setSelectedId(id); window.localStorage.setItem("medley-demo-student", id); setSwitcherOpen(false); };
  const personalizedSubjects = student?.subjects_studying.length ? student.subjects_studying : ["Internal Medicine", "Pharmacology"];
  const weakAreas = student?.weak_areas.length ? student.weak_areas : ["Pharmacology", "Clinical Skills"];
  const minutes = student?.daily_study_target_minutes ?? 30;
  const recommendations = [
    { type: "CASE", title: `${personalizedSubjects[0]}: clinical reasoning`, description: "Work through a patient presentation", icon: HeartPulse, color: "lavender", tab: "Cases" },
    { type: "QUIZ", title: `${weakAreas[0]} essentials`, description: "10 quick questions · 8 min", icon: Brain, color: "blue", tab: "Quizzes" },
    { type: "OSCE", title: "Focused history taking", description: "Communication · 12 min", icon: Stethoscope, color: "pink", tab: "OSCE" },
    { type: "DECK", title: `${personalizedSubjects.at(-1)} quick recall`, description: "Review 18 high-yield cards", icon: Layers3, color: "yellow", tab: "Flashcards" },
  ];

  return <div className="min-h-screen pb-28 md:pb-10">
    <header className="sticky top-0 z-30 bg-background/95 backdrop-blur-sm">
      <div className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-5 py-4 md:px-8 md:py-5">
        <Link to="/" className="flex items-center gap-2.5 font-display text-[26px] font-black text-foreground" aria-label="Medley home"><span className="flex size-10 items-center justify-center rounded-2xl bg-pink text-foreground shadow-sm"><HeartPulse size={23} strokeWidth={2.5}/></span>medley<span className="text-pink">.</span></Link>
        <div className="hidden items-center gap-1 md:flex">{nav.map(item => <Link key={item.label} to={item.to} className={`rounded-full px-4 py-2 text-sm font-extrabold transition-colors ${view === item.label.toLowerCase() ? "bg-lavender-soft text-foreground" : "text-muted-foreground hover:bg-muted hover:text-foreground"}`}>{item.label}</Link>)}</div>
        <div className="relative">
          <Button variant="secondary" onClick={() => setSwitcherOpen(!switcherOpen)} aria-expanded={switcherOpen} aria-label="Choose acting as student" className="h-11 max-w-[190px] gap-2 bg-card px-2 pr-3 shadow-sm hover:bg-card md:max-w-none">
            <span className="flex size-8 shrink-0 items-center justify-center rounded-full bg-mint text-xs font-black">{student ? initials(student.name) : "?"}</span><span className="min-w-0 truncate text-left text-xs md:text-sm"><span className="block text-[10px] font-bold leading-none text-muted-foreground">ACTING AS</span>{loading ? "Loading..." : firstName(student?.name)}</span><ChevronDown size={15} className="shrink-0"/>
          </Button>
          {switcherOpen && <><div className="fixed inset-0 z-30" onClick={() => setSwitcherOpen(false)}/><div className="absolute right-0 top-14 z-40 w-[min(85vw,290px)] rounded-[22px] bg-card p-2 shadow-xl"><p className="px-3 pb-2 pt-2 text-xs font-extrabold uppercase text-muted-foreground">Switch student</p>{students.map(item => <Button key={item.id} variant="ghost" onClick={() => selectStudent(item.id)} className={`h-auto w-full justify-start gap-3 whitespace-normal rounded-2xl px-3 py-2 text-left ${item.id === student?.id ? "bg-mint-soft" : ""}`}><span className="flex size-9 shrink-0 items-center justify-center rounded-full bg-lavender-soft text-xs">{initials(item.name)}</span><span className="min-w-0"><span className="block truncate text-sm font-extrabold">{item.name}</span><span className="block truncate text-xs font-medium text-muted-foreground">Year {item.year_of_study} · {item.university}</span></span></Button>)}<div className="my-1 h-px bg-border"/><Button variant="ghost" onClick={() => { setSwitcherOpen(false); setOnboarding(true); }} className="w-full justify-start gap-3 rounded-2xl px-3 text-sm"><Plus size={18}/>Create demo profile</Button></div></>}
        </div>
      </div>
    </header>
    <main className="mx-auto max-w-7xl px-5 pt-6 md:px-8 md:pt-8">
      {loadError && <div className="mb-5 rounded-2xl bg-pink-soft p-4 text-sm font-bold">{loadError}</div>}
      {view === "home" && <>
        <div className="mb-8 flex flex-wrap items-end justify-between gap-3"><div><p className="mb-2 flex items-center gap-1.5 text-sm font-extrabold text-ink-soft"><Sparkles size={16} className="text-pink"/> YOUR STUDY SPACE</p><h1 className="font-display text-3xl font-black leading-tight md:text-5xl">Good to see you, {firstName(student?.name)} <span aria-hidden="true">✳</span></h1><p className="mt-2 text-base text-muted-foreground md:text-lg">What should I study today?</p></div><div className="hidden items-center gap-2 rounded-full bg-yellow-soft px-4 py-2 text-sm font-extrabold md:flex"><Flame size={18} className="text-pink"/>{student?.streak_days ?? 0} day streak</div></div>
        <div className="grid gap-5 lg:grid-cols-[minmax(0,1.7fr)_minmax(300px,1fr)]">
          <div className="space-y-6">
            <section className="clay-card relative min-h-[295px] overflow-hidden bg-lavender-soft p-6 md:min-h-[320px] md:p-8"><div className="relative z-10 max-w-[65%] md:max-w-[60%]"><span className="inline-flex rounded-full bg-card/75 px-3 py-1 text-[11px] font-black uppercase tracking-wider text-ink-soft">✦ Weekly case</span><h2 className="mt-5 font-display text-2xl font-black leading-tight md:text-4xl">A breathless patient in the emergency unit</h2><p className="mt-3 text-sm leading-relaxed text-ink-soft md:text-base">A 42-year-old arrives with sudden shortness of breath. What will you do first?</p><div className="mt-4 flex flex-wrap gap-x-4 gap-y-1 text-xs font-bold text-ink-soft"><span>Intermediate</span><span>⏱ 20 min</span><span>👥 128 taking part</span></div><Button variant="lavender" className="mt-5" onClick={() => setActivity("The clinical case simulator is coming in a later step. Your weekly case will appear here when it is ready.")}>Start case <ArrowRight size={17}/></Button></div><img src={heartImage} width={1024} height={1024} alt="Soft clay model of a human heart" className="absolute -right-16 bottom-0 h-[240px] w-[240px] object-cover mix-blend-multiply md:-right-4 md:-bottom-4 md:h-[320px] md:w-[320px]"/><div className="absolute bottom-5 left-6 z-10 hidden text-xs font-bold text-ink-soft md:block">Ends Sunday · 3 days left</div></section>
            <section><SectionHeading title="Pick up where you left off"/><div className="grid gap-4 sm:grid-cols-2"><button onClick={() => setActivity("Your in-progress case will be available when the simulator arrives.")} className="clay-card flex w-full items-center gap-4 bg-card p-5 text-left"><IconBubble icon={HeartPulse}/><div className="min-w-0 flex-1"><p className="text-xs font-extrabold uppercase text-muted-foreground">Case · In progress</p><h3 className="mt-1 truncate font-display font-black">Chest pain assessment</h3><p className="mt-1 text-xs text-muted-foreground">About 10 min remaining</p></div><ChevronRight size={18}/></button><button onClick={() => setActivity("Your quiz sessions will appear here in a later step.")} className="clay-card flex w-full items-center gap-4 bg-card p-5 text-left"><IconBubble icon={Brain} color="blue"/><div className="min-w-0 flex-1"><p className="text-xs font-extrabold uppercase text-muted-foreground">Quiz · In progress</p><h3 className="mt-1 truncate font-display font-black">{weakAreas[0]} review</h3><p className="mt-1 text-xs text-muted-foreground">Question 6 of 10</p></div><ChevronRight size={18}/></button></div></section>
            <section><SectionHeading title="Recommended for you" action="Explore practice" to="/practice"/><div className="grid gap-3 sm:grid-cols-2">{recommendations.map(item => <button key={item.type} onClick={() => setActivity(`${item.tab} activities are being prepared for a later step.`)} className={`clay-card flex items-start gap-3 bg-${item.color}-soft p-4 text-left md:p-5`}><IconBubble icon={item.icon} color={item.color}/><div><p className="text-[11px] font-black uppercase text-ink-soft">{item.type}</p><h3 className="mt-1 font-display text-base font-black leading-snug">{item.title}</h3><p className="mt-1 text-xs text-ink-soft">{item.description}</p></div></button>)}</div></section>
            <section><SectionHeading title="Your weak areas"/><div className="clay-card bg-card p-5 md:p-6"><p className="mb-5 text-sm text-muted-foreground">A little extra practice here can make a big difference.</p>{weakAreas.slice(0,3).map((subject, i) => { const score = [54, 63, 71][i]; return <div key={subject} className="mb-4 last:mb-0"><div className="mb-2 flex justify-between gap-2 text-sm font-bold"><span>{subject}</span><span className="text-ink-soft">{score}%</span></div><div className="h-2.5 rounded-full bg-muted soft-inset"><div className={`h-full rounded-full ${i === 0 ? "bg-pink" : i === 1 ? "bg-yellow" : "bg-mint"}`} style={{ width: `${score}%` }}/></div></div>; })}</div></section>
          </div>
          <div className="space-y-6">
            <section className="clay-card bg-card p-6"><div className="mb-5 flex items-center justify-between"><h2 className="font-display text-xl font-black">Study progress</h2><IconBubble icon={Target} color="pink"/></div><div className="flex items-center gap-5"><div className="relative flex size-[112px] shrink-0 items-center justify-center rounded-full progress-gradient p-[10px]"><div className="flex size-full flex-col items-center justify-center rounded-full bg-card"><span className="font-display text-2xl font-black">0<span className="text-sm">/{minutes}</span></span><span className="text-[11px] font-bold text-muted-foreground">min today</span></div></div><div className="space-y-2"><p className="text-sm font-bold">Your daily goal</p><p className="text-sm leading-relaxed text-muted-foreground">Small steps add up. You've got this!</p></div></div><div className="mt-6 grid grid-cols-3 gap-2 border-t border-border pt-5 text-center"><div><p className="font-display text-xl font-black">{student?.xp ?? 0}</p><p className="text-xs text-muted-foreground">XP</p></div><div><p className="font-display text-xl font-black">{student?.level ?? 1}</p><p className="text-xs text-muted-foreground">Level</p></div><div><p className="flex items-center justify-center gap-1 font-display text-xl font-black"><Flame size={17} className="text-pink"/>{student?.streak_days ?? 0}</p><p className="text-xs text-muted-foreground">Streak</p></div></div><div className="mt-5"><div className="mb-2 flex justify-between text-xs font-extrabold"><span>Weekly goal</span><span>0 / {Math.round(minutes * 7 / 60)} hrs</span></div><div className="h-2.5 rounded-full bg-muted soft-inset"><div className="h-full w-0 rounded-full progress-gradient"/></div></div></section>
            <section className="clay-card bg-yellow-soft p-6"><div className="flex items-start justify-between"><div><p className="text-xs font-black uppercase text-ink-soft">Quick review</p><h2 className="mt-1 font-display text-xl font-black">Flashcards due</h2></div><IconBubble icon={Layers3} color="yellow"/></div><div className="my-5 flex items-end gap-2"><span className="font-display text-5xl font-black">18</span><span className="pb-1 text-sm font-bold text-ink-soft">cards · about 8 min</span></div><Button variant="yellow" className="w-full" onClick={() => setActivity("Flashcard reviews are coming in a later step.")}>Review now <ArrowRight size={17}/></Button></section>
            <section className="clay-card bg-mint-soft p-6"><div className="flex items-center justify-between"><h2 className="font-display text-xl font-black">Group activity</h2><IconBubble icon={Users} color="mint"/></div><div className="mt-5 space-y-4"><div className="flex gap-3"><span className="flex size-9 shrink-0 items-center justify-center rounded-full bg-card text-sm">👋</span><div><p className="text-sm font-bold">Clinical Skills study circle</p><p className="text-xs text-ink-soft">Practice session this Friday</p></div></div><div className="flex gap-3"><span className="flex size-9 shrink-0 items-center justify-center rounded-full bg-card text-sm">✨</span><div><p className="text-sm font-bold">Weekly quiz challenge</p><p className="text-xs text-ink-soft">Your group is waiting for you</p></div></div></div><Link to="/groups" className="mt-5 inline-flex items-center gap-1 text-sm font-extrabold">View groups <ArrowRight size={16}/></Link></section>
            <section className="clay-card bg-pink-soft p-6"><div className="flex items-center justify-between"><h2 className="font-display text-xl font-black">Achievements</h2><IconBubble icon={Trophy} color="pink"/></div><div className="mt-5 flex items-center gap-3"><span className="flex size-14 items-center justify-center rounded-2xl bg-yellow text-2xl shadow-sm">🏅</span><div><p className="font-display font-black">Getting into the rhythm</p><p className="text-sm text-ink-soft">{student?.streak_days ?? 0}-day study streak</p></div></div></section>
          </div>
        </div>
      </>}
      {view === "cases" && <div className="max-w-4xl"><PageIntro eyebrow="CLINICAL REASONING" title="Clinical cases" description="Think like a clinician, one decision at a time." icon={HeartPulse} color="lavender"/><section className="clay-card relative mt-8 overflow-hidden bg-lavender-soft p-6 md:p-9"><div className="relative z-10 max-w-md"><span className="rounded-full bg-card px-3 py-1 text-xs font-black">THIS WEEK'S CASE</span><h2 className="mt-5 font-display text-2xl font-black md:text-3xl">A breathless patient in the emergency unit</h2><p className="mt-3 text-sm leading-relaxed text-ink-soft">Intermediate · 20 min · 128 participants</p><Button variant="lavender" onClick={() => setActivity("The interactive case simulator is coming in a later step.")} className="mt-6">Start case <ArrowRight/></Button></div><img src={heartImage} width={1024} height={1024} alt="Clay model of a heart" className="absolute -bottom-12 -right-20 h-64 w-64 object-cover mix-blend-multiply md:-right-5"/></section><div className="mt-10"><SectionHeading title="More to explore"/><div className="clay-card bg-card p-6"><EmptyAction label="More clinical cases will appear here as the case library grows."/></div></div></div>}
      {view === "practice" && <div className="max-w-5xl"><PageIntro eyebrow="YOUR PRACTICE SPACE" title="Practice your way" description="Short, focused sessions for every part of your learning." icon={Stethoscope} color="pink"/><div className="mt-8 flex gap-2 overflow-x-auto pb-2">{(["OSCE", "Quizzes", "Flashcards"] as PracticeTab[]).map(tab => <Button key={tab} variant={practiceTab === tab ? tab === "OSCE" ? "pink" : tab === "Quizzes" ? "blue" : "yellow" : "secondary"} onClick={() => setPracticeTab(tab)} className="shrink-0">{tab === "OSCE" ? <Stethoscope/> : tab === "Quizzes" ? <Brain/> : <Layers3/>}{tab}</Button>)}</div><section className={`clay-card mt-5 bg-${practiceTab === "OSCE" ? "pink" : practiceTab === "Quizzes" ? "blue" : "yellow"}-soft p-6 md:p-9`}><div className="flex items-start gap-4"><IconBubble icon={practiceTab === "OSCE" ? Stethoscope : practiceTab === "Quizzes" ? Brain : Layers3} color={practiceTab === "OSCE" ? "pink" : practiceTab === "Quizzes" ? "blue" : "yellow"}/><div><h2 className="font-display text-2xl font-black">{practiceTab === "OSCE" ? "OSCE stations" : practiceTab === "Quizzes" ? "Quick quizzes" : "Flashcard decks"}</h2><p className="mt-2 max-w-xl text-sm leading-relaxed text-ink-soft">{practiceTab === "OSCE" ? "Practice focused histories, examinations, and communication." : practiceTab === "Quizzes" ? "Test your understanding with bite-sized questions." : "Keep the important details fresh with quick review sessions."}</p></div></div><div className="mt-8 rounded-2xl bg-card/70 p-5"><p className="text-sm font-bold">{practiceTab === "OSCE" ? "Focused history taking" : practiceTab === "Quizzes" ? `${weakAreas[0]} essentials` : `${personalizedSubjects[0]} quick recall`}</p><p className="mt-1 text-xs text-muted-foreground">{practiceTab === "OSCE" ? "Communication · 12 min" : practiceTab === "Quizzes" ? "10 questions · 8 min" : "18 cards · 8 min"}</p><Button variant={practiceTab === "OSCE" ? "pink" : practiceTab === "Quizzes" ? "blue" : "yellow"} className="mt-5" onClick={() => setActivity(`${practiceTab} activities are coming in a later step.`)}>Start practice <ArrowRight/></Button></div></section></div>}
      {view === "groups" && <div className="max-w-4xl"><PageIntro eyebrow="LEARN TOGETHER" title="Study groups" description="A little help from your people goes a long way." icon={Users} color="mint"/><div className="mt-8 grid gap-4 sm:grid-cols-2"><div className="clay-card bg-mint-soft p-6"><IconBubble icon={Users} color="mint"/><h2 className="mt-5 font-display text-xl font-black">Clinical Skills study circle</h2><p className="mt-2 text-sm text-ink-soft">Practice session this Friday · 8 members</p><Button variant="mint" className="mt-6" onClick={() => setActivity("Group sessions are coming in a later step.")}>View group <ArrowRight/></Button></div><div className="clay-card bg-card p-6"><IconBubble icon={Trophy} color="yellow"/><h2 className="mt-5 font-display text-xl font-black">Weekly quiz challenge</h2><p className="mt-2 text-sm text-ink-soft">A friendly challenge with your study circle</p><Button variant="secondary" className="mt-6" onClick={() => setActivity("Group challenges are coming in a later step.")}>See challenge <ArrowRight/></Button></div></div></div>}
      {view === "profile" && <div className="max-w-4xl"><PageIntro eyebrow="YOUR STUDY JOURNEY" title="Student profile" description="A snapshot of where you are and where you want to go." icon={Activity} color="blue"/><div className="mt-8 grid gap-5 md:grid-cols-2"><div className="clay-card bg-card p-6"><div className="flex items-center gap-4"><span className="flex size-16 items-center justify-center rounded-3xl bg-mint font-display text-xl font-black">{student ? initials(student.name) : "?"}</span><div><h2 className="font-display text-xl font-black">{student?.name ?? "Loading student"}</h2><p className="text-sm text-muted-foreground">Year {student?.year_of_study} · {student?.medical_program}</p></div></div><div className="mt-6 space-y-4 text-sm"><InfoRow label="University" value={student?.university ?? "—"}/><InfoRow label="Country" value={student?.country ?? "—"}/><InfoRow label="Current rotation" value={student?.current_rotation ?? "Not set"}/><InfoRow label="Study goal" value={student?.study_goal ?? "Not set"}/><InfoRow label="Daily target" value={`${minutes} minutes`}/></div></div><div className="clay-card bg-lavender-soft p-6"><h2 className="font-display text-xl font-black">Learning focus</h2><p className="mt-5 text-xs font-extrabold uppercase text-ink-soft">Studying now</p><div className="mt-2 flex flex-wrap gap-2">{personalizedSubjects.map(subject => <span key={subject} className="rounded-full bg-card px-3 py-1.5 text-xs font-bold">{subject}</span>)}</div><p className="mt-6 text-xs font-extrabold uppercase text-ink-soft">Interested in</p><div className="mt-2 flex flex-wrap gap-2">{student?.specialty_interests.length ? student.specialty_interests.map(subject => <span key={subject} className="rounded-full bg-card px-3 py-1.5 text-xs font-bold">{subject}</span>) : <span className="text-sm">Not set</span>}</div><p className="mt-6 text-xs font-extrabold uppercase text-ink-soft">Needs more practice</p><div className="mt-2 flex flex-wrap gap-2">{weakAreas.map(subject => <span key={subject} className="rounded-full bg-card px-3 py-1.5 text-xs font-bold">{subject}</span>)}</div></div><div className="clay-card progress-gradient p-6 md:col-span-2"><div className="grid grid-cols-3 gap-4 text-center"><div><p className="font-display text-3xl font-black">{student?.xp ?? 0}</p><p className="text-xs font-bold">Total XP</p></div><div><p className="font-display text-3xl font-black">{student?.level ?? 1}</p><p className="text-xs font-bold">Level</p></div><div><p className="font-display text-3xl font-black">{student?.streak_days ?? 0}</p><p className="text-xs font-bold">Day streak</p></div></div></div></div></div>}
    </main>
    <nav aria-label="Main navigation" className="fixed bottom-0 left-0 right-0 z-20 rounded-t-[24px] bg-card px-2 pb-[max(10px,env(safe-area-inset-bottom))] pt-2 shadow-[0_-8px_30px_-14px_var(--border)] md:hidden"><div className="mx-auto flex max-w-lg items-center justify-around">{nav.map(item => { const Icon = item.icon; const active = view === item.label.toLowerCase(); return <Link key={item.label} to={item.to} className={`flex min-w-[58px] flex-col items-center gap-1 rounded-2xl px-2 py-2 text-[10px] font-extrabold transition-colors ${active ? "bg-lavender-soft text-foreground" : "text-muted-foreground"}`}><Icon size={21} strokeWidth={active ? 2.5 : 2}/>{item.label}</Link>; })}</div></nav>
    {activity && <div className="fixed inset-0 z-50 flex items-center justify-center bg-foreground/25 p-5" onClick={() => setActivity(null)}><div role="dialog" aria-modal="true" aria-label="Coming soon" className="clay-card w-full max-w-sm bg-card p-7 text-center" onClick={e => e.stopPropagation()}><span className="mx-auto flex size-14 items-center justify-center rounded-2xl bg-lavender-soft"><Sparkles/></span><h2 className="mt-4 font-display text-xl font-black">Coming soon</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{activity}</p><Button onClick={() => setActivity(null)} className="mt-6 w-full">Got it</Button></div></div>}
    {onboarding && <Onboarding onClose={() => setOnboarding(false)} onCreated={(created) => { setStudents(prev => [...prev, created]); selectStudent(created.id); setOnboarding(false); }}/ >}
  </div>;
}

function PageIntro({ eyebrow, title, description, icon: Icon, color }: { eyebrow: string; title: string; description: string; icon: typeof Home; color: string }) { return <div><div className="flex items-center gap-2 text-xs font-black uppercase text-ink-soft"><Icon size={17} className={`text-${color}`}/>{eyebrow}</div><h1 className="mt-3 font-display text-3xl font-black md:text-5xl">{title}</h1><p className="mt-3 text-base text-muted-foreground md:text-lg">{description}</p></div>; }
function InfoRow({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4 border-b border-border pb-3 last:border-0"><span className="text-muted-foreground">{label}</span><span className="max-w-[60%] text-right font-bold">{value}</span></div>; }

type Form = { name: string; email: string; university: string; country: string; year: string; program: string; subjects: string[]; rotation: string; interests: string; weak: string; goal: string; target: string; reminders: boolean; digest: boolean };
const initialForm: Form = { name: "", email: "", university: "", country: "Rwanda", year: "", program: "MBBS", subjects: [], rotation: "", interests: "", weak: "", goal: "", target: "30", reminders: true, digest: false };
function Onboarding({ onClose, onCreated }: { onClose: () => void; onCreated: (student: Student) => void }) {
  const [step, setStep] = useState(0);
  const [form, setForm] = useState<Form>(initialForm);
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const titles = ["Let's start with you", "Where are you studying?", "What's on your study list?", "Shape your study space"];
  const descriptions = ["Just the basics for your demo profile.", "Tell us about your medical journey.", "Pick the subjects you're working on right now.", "These are optional — you can leave them blank."];
  const update = (key: keyof Form, value: Form[keyof Form]) => setForm(prev => ({ ...prev, [key]: value }));
  const input = (label: string, key: keyof Form, placeholder: string, type = "text", required = false) => <label className="block text-sm font-extrabold">{label}<input type={type} value={String(form[key])} onChange={e => update(key, e.target.value)} placeholder={placeholder} required={required} className="mt-2 block h-12 w-full rounded-2xl bg-muted px-4 font-medium outline-none ring-primary focus:ring-2"/></label>;
  async function next() {
    setError("");
    if (step === 0 && (!form.name.trim() || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email.trim()))) { setError("Please enter your name and a valid email address."); return; }
    if (step === 1 && (!form.university.trim() || !form.country.trim() || !form.year || !form.program.trim())) { setError("Please complete your school, country, year and program."); return; }
    if (step === 2 && form.subjects.length === 0) { setError("Choose at least one subject you're studying."); return; }
    if (step < 3) { setStep(step + 1); return; }
    const target = Number(form.target);
    if (!Number.isInteger(target) || target < 5 || target > 480) { setError("Choose a daily target between 5 and 480 minutes."); return; }
    setSaving(true);
    const values = { name: form.name.trim(), email: form.email.trim(), university: form.university.trim(), country: form.country.trim(), year_of_study: Number(form.year), medical_program: form.program.trim(), current_level: Number(form.year) <= 2 ? "Pre-clinical" : "Clinical years", subjects_studying: form.subjects, current_rotation: form.rotation.trim() || null, specialty_interests: form.interests.split(",").map(x => x.trim()).filter(Boolean), weak_areas: form.weak.split(",").map(x => x.trim()).filter(Boolean), study_goal: form.goal.trim() || null, daily_study_target_minutes: target, notification_prefs: { study_reminders: form.reminders, weekly_digest: form.digest } };
    const { error: insertError } = await supabase.from("students").insert(values);
    if (insertError) { setError("We couldn't create your demo profile. Please try again."); setSaving(false); return; }
    const { data, error: readError } = await supabase.from("students").select(columns).eq("email", form.email.trim()).order("created_at", { ascending: false }).limit(1);
    // Email is not publicly readable; refresh the safe directory and match by recently-created name.
    if (readError || !data?.length) {
      const { data: directory } = await supabase.from("students").select(columns).order("created_at", { ascending: false }).limit(30);
      const created = (directory as Student[] | null)?.find(item => item.name === form.name.trim() && item.university === form.university.trim());
      if (created) { onCreated(created); return; }
      setError("Profile created, but it couldn't be selected. Refresh to find it in the student switcher."); setSaving(false); return;
    }
    onCreated(data[0] as Student);
  }
  return <div className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-foreground/25 p-4" role="dialog" aria-modal="true" aria-label="Create demo profile"><div className="clay-card my-auto w-full max-w-lg bg-card p-6 md:p-8"><div className="flex items-center justify-between"><span className="text-xs font-black uppercase text-muted-foreground">Create demo profile · {step + 1} of 4</span><Button variant="ghost" size="icon" aria-label="Close" onClick={onClose}><X/></Button></div><div className="mt-4 flex gap-2">{titles.map((_, i) => <div key={i} className={`h-2 flex-1 rounded-full ${i <= step ? "bg-lavender" : "bg-muted"}`}/>)}</div><h2 className="mt-7 font-display text-2xl font-black md:text-3xl">{titles[step]}</h2><p className="mt-1 text-sm text-muted-foreground">{descriptions[step]}</p><div className="mt-7 max-h-[48vh] space-y-4 overflow-y-auto pr-1">
    {step === 0 && <>{input("Your name", "name", "e.g. Aline Uwimana", "text", true)}{input("Email address", "email", "you@example.com", "email", true)}</>}
    {step === 1 && <>{input("University", "university", "e.g. University of Rwanda", "text", true)}{input("Country", "country", "Rwanda", "text", true)}<label className="block text-sm font-extrabold">Year of study<select value={form.year} onChange={e => update("year", e.target.value)} className="mt-2 block h-12 w-full rounded-2xl bg-muted px-4 font-medium outline-none ring-primary focus:ring-2"><option value="">Select year</option>{Array.from({length:8}, (_,i) => <option key={i} value={i+1}>Year {i+1}</option>)}</select></label>{input("Medical program", "program", "e.g. MBBS", "text", true)}</>}
    {step === 2 && <div className="flex flex-wrap gap-2">{subjects.map(subject => { const chosen = form.subjects.includes(subject); return <Button key={subject} variant={chosen ? "lavender" : "secondary"} onClick={() => update("subjects", chosen ? form.subjects.filter(item => item !== subject) : [...form.subjects, subject])} className="h-10 text-xs">{chosen && <CircleCheck size={15}/ >}{subject}</Button>; })}</div>}
    {step === 3 && <>{input("Current rotation", "rotation", "e.g. Paediatrics")}{input("Specialty interests", "interests", "e.g. Cardiology, Emergency Medicine")}{input("Areas to work on", "weak", "e.g. Pharmacology, Anatomy")}{input("Study goal", "goal", "What would you like to achieve?")}{input("Daily study target (minutes)", "target", "30", "number")}<div className="rounded-2xl bg-muted p-4"><p className="mb-3 text-sm font-extrabold">Notifications</p><label className="flex items-center justify-between gap-3 py-1 text-sm">Study reminders<input type="checkbox" checked={form.reminders} onChange={e => update("reminders", e.target.checked)} className="size-5 accent-primary"/></label><label className="flex items-center justify-between gap-3 py-1 text-sm">Weekly digest<input type="checkbox" checked={form.digest} onChange={e => update("digest", e.target.checked)} className="size-5 accent-primary"/></label></div></>}
  </div>{error && <p role="alert" className="mt-4 text-sm font-bold text-pink">{error}</p>}<div className="mt-7 flex gap-3">{step > 0 && <Button variant="secondary" onClick={() => { setError(""); setStep(step - 1); }}><ArrowLeft/> Back</Button>}<Button className="flex-1" disabled={saving} onClick={next}>{saving ? "Creating..." : step === 3 ? "Create profile" : "Continue"}<ArrowRight/></Button></div></div></div>;
}
