/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as OsceRouteImport } from './routes/osce'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'
import { Route as OsceIndexRouteImport } from './routes/osce.index'
import { Route as OsceStationIdRouteImport } from './routes/osce.$stationId'
import { Route as OsceExamRouteImport } from './routes/osce.exam'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const OsceRoute = OsceRouteImport.update({
  id: '/osce',
  path: '/osce',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CasesRoute,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => CasesRoute,
} as any)
const OsceIndexRoute = OsceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OsceRoute,
} as any)
const OsceStationIdRoute = OsceStationIdRouteImport.update({
  id: '/$stationId',
  path: '/$stationId',
  getParentRoute: () => OsceRoute,
} as any)
const OsceExamRoute = OsceExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => OsceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRouteWithChildren
  '/groups': typeof GroupsRoute
  '/osce': typeof OsceRouteWithChildren
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/osce/$stationId': typeof OsceStationIdRoute
  '/osce/exam': typeof OsceExamRoute
  '/cases/': typeof CasesIndexRoute
  '/osce/': typeof OsceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/groups': typeof GroupsRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/osce/$stationId': typeof OsceStationIdRoute
  '/osce/exam': typeof OsceExamRoute
  '/cases': typeof CasesIndexRoute
  '/osce': typeof OsceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases': typeof CasesRouteWithChildren
  '/groups': typeof GroupsRoute
  '/osce': typeof OsceRouteWithChildren
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/osce/$stationId': typeof OsceStationIdRoute
  '/osce/exam': typeof OsceExamRoute
  '/cases/': typeof CasesIndexRoute
  '/osce/': typeof OsceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases'
    | '/groups'
    | '/osce'
    | '/practice'
    | '/profile'
    | '/cases/$caseId'
    | '/osce/$stationId'
    | '/osce/exam'
    | '/cases/'
    | '/osce/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/groups'
    | '/practice'
    | '/profile'
    | '/cases/$caseId'
    | '/osce/$stationId'
    | '/osce/exam'
    | '/cases'
    | '/osce'
  id:
    | '__root__'
    | '/'
    | '/cases'
    | '/groups'
    | '/osce'
    | '/practice'
    | '/profile'
    | '/cases/$caseId'
    | '/osce/$stationId'
    | '/osce/exam'
    | '/cases/'
    | '/osce/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRoute: typeof CasesRouteWithChildren
  GroupsRoute: typeof GroupsRoute
  OsceRoute: typeof OsceRouteWithChildren
  PracticeRoute: typeof PracticeRoute
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/osce': {
      id: '/osce'
      path: '/osce'
      fullPath: '/osce'
      preLoaderRoute: typeof OsceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof CasesRoute
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof CasesRoute
    }
    '/osce/': {
      id: '/osce/'
      path: '/'
      fullPath: '/osce/'
      preLoaderRoute: typeof OsceIndexRouteImport
      parentRoute: typeof OsceRoute
    }
    '/osce/$stationId': {
      id: '/osce/$stationId'
      path: '/$stationId'
      fullPath: '/osce/$stationId'
      preLoaderRoute: typeof OsceStationIdRouteImport
      parentRoute: typeof OsceRoute
    }
    '/osce/exam': {
      id: '/osce/exam'
      path: '/exam'
      fullPath: '/osce/exam'
      preLoaderRoute: typeof OsceExamRouteImport
      parentRoute: typeof OsceRoute
    }
  }
}

interface CasesRouteChildren {
  CasesCaseIdRoute: typeof CasesCaseIdRoute
  CasesIndexRoute: typeof CasesIndexRoute
}

const CasesRouteChildren: CasesRouteChildren = {
  CasesCaseIdRoute: CasesCaseIdRoute,
  CasesIndexRoute: CasesIndexRoute,
}

const CasesRouteWithChildren = CasesRoute._addFileChildren(CasesRouteChildren)

interface OsceRouteChildren {
  OsceStationIdRoute: typeof OsceStationIdRoute
  OsceExamRoute: typeof OsceExamRoute
  OsceIndexRoute: typeof OsceIndexRoute
}

const OsceRouteChildren: OsceRouteChildren = {
  OsceStationIdRoute: OsceStationIdRoute,
  OsceExamRoute: OsceExamRoute,
  OsceIndexRoute: OsceIndexRoute,
}

const OsceRouteWithChildren = OsceRoute._addFileChildren(OsceRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesRoute: CasesRouteWithChildren,
  GroupsRoute: GroupsRoute,
  OsceRoute: OsceRouteWithChildren,
  PracticeRoute: PracticeRoute,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
